//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class RIMS_V2_MainForm {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal RIMS_V2_MainForm() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RIMS_V2.MainForm", typeof(RIMS_V2_MainForm).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap A0_Image {
        get {
            object obj = ResourceManager.GetObject("A0.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap A1_Image {
        get {
            object obj = ResourceManager.GetObject("A1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap A2_Image {
        get {
            object obj = ResourceManager.GetObject("A2.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap A3_Image {
        get {
            object obj = ResourceManager.GetObject("A3.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap A4_Image {
        get {
            object obj = ResourceManager.GetObject("A4.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap A5_Image {
        get {
            object obj = ResourceManager.GetObject("A5.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap A6_Image {
        get {
            object obj = ResourceManager.GetObject("A6.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap A7_Image {
        get {
            object obj = ResourceManager.GetObject("A7.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap B0_Image {
        get {
            object obj = ResourceManager.GetObject("B0.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap B1_Image {
        get {
            object obj = ResourceManager.GetObject("B1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap B2_Image {
        get {
            object obj = ResourceManager.GetObject("B2.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap B3_Image {
        get {
            object obj = ResourceManager.GetObject("B3.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap B4_Image {
        get {
            object obj = ResourceManager.GetObject("B4.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap B5_Image {
        get {
            object obj = ResourceManager.GetObject("B5.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap B6_Image {
        get {
            object obj = ResourceManager.GetObject("B6.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap B7_Image {
        get {
            object obj = ResourceManager.GetObject("B7.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
    /// </summary>
    public static System.Drawing.Icon favicon {
        get {
            object obj = ResourceManager.GetObject("favicon", resourceCulture);
            return ((System.Drawing.Icon)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
    /// </summary>
    public static System.Drawing.Icon Icon3 {
        get {
            object obj = ResourceManager.GetObject("Icon3", resourceCulture);
            return ((System.Drawing.Icon)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
    /// </summary>
    public static System.Drawing.Icon Icon4 {
        get {
            object obj = ResourceManager.GetObject("Icon4", resourceCulture);
            return ((System.Drawing.Icon)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
    /// </summary>
    public static System.Drawing.Icon MainIcon {
        get {
            object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
            return ((System.Drawing.Icon)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pictureBox1_Image {
        get {
            object obj = ResourceManager.GetObject("pictureBox1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pictureBox2_Image {
        get {
            object obj = ResourceManager.GetObject("pictureBox2.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pictureBox3_Image {
        get {
            object obj = ResourceManager.GetObject("pictureBox3.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pictureBox4_Image {
        get {
            object obj = ResourceManager.GetObject("pictureBox4.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pictureBox5_Image {
        get {
            object obj = ResourceManager.GetObject("pictureBox5.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pictureBox6_Image {
        get {
            object obj = ResourceManager.GetObject("pictureBox6.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pictureBox7_Image {
        get {
            object obj = ResourceManager.GetObject("pictureBox7.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pictureBox8_Image {
        get {
            object obj = ResourceManager.GetObject("pictureBox8.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pictureBox9_Image {
        get {
            object obj = ResourceManager.GetObject("pictureBox9.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap R_pin_0_Image {
        get {
            object obj = ResourceManager.GetObject("R_pin_0.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap R_pin_1_Image {
        get {
            object obj = ResourceManager.GetObject("R_pin_1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap R_pin_2_Image {
        get {
            object obj = ResourceManager.GetObject("R_pin_2.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap R_pin_3_Image {
        get {
            object obj = ResourceManager.GetObject("R_pin_3.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap R_pin_4_Image {
        get {
            object obj = ResourceManager.GetObject("R_pin_4.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap R_pin_5_Image {
        get {
            object obj = ResourceManager.GetObject("R_pin_5.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap R_pin_6_Image {
        get {
            object obj = ResourceManager.GetObject("R_pin_6.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap R_pin_7_Image {
        get {
            object obj = ResourceManager.GetObject("R_pin_7.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap tabPage1_BackgroundImage {
        get {
            object obj = ResourceManager.GetObject("tabPage1.BackgroundImage", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to b00000000
    ///wait 1 s
    ///3
    ///wait 1 s
    ///assert 1
    ///assert b00000001
    ///assert 0x01
    ///wait 0.5 s
    ///b00000010
    ///wait 3000 ms
    ///b11111101
    ///wait 200 ms
    ///b00010101
    ///wait 500 ms
    ///b11000011
    ///wait 2 s
    ///b01000010
    ///wait 1 s
    ///0xFF
    ///wait 1 s
    ///generatetd.
    /// </summary>
    public static string testVectorText_Text {
        get {
            return ResourceManager.GetString("testVectorText.Text", resourceCulture);
        }
    }
}
